language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew build test

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  on:
    tags: true
